name: Test Vorfreude

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      # fix --cwd after svelte migration
      - run: yarn --cwd ./svelte
      - run: yarn --cwd ./svelte test
